#ifndef BIGI_FORWARD_ADD_PRAGMA
#define BIGI_FORWARD_ADD_PRAGMA
#include_with_pragmas "./Global.cginc"

//#pragma multi_compile_fwdadd_fullshadows
#pragma multi_compile POINT DIRECTIONAL SPOT POINT_COOKIE DIRECTIONAL_COOKIE SHADOWS_DEPTH SHADOWS_SCREEN SHADOWS_CUBE SHADOWS_SOFT SHADOWS_SHADOWMASK

#endif