#ifndef BIGI_FORWARD_ADD_PRAGMA
#define BIGI_FORWARD_ADD_PRAGMA
#include_with_pragmas "./Global.cginc"

#pragma multi_compile_fwdadd_fullshadows
#pragma multi_compile_instancing

#pragma skip_variants LIGHTMAP_ON DYNAMICLIGHTMAP_ON LIGHTMAP_SHADOW_MIXING SHADOWS_SHADOWMASK DIRLIGHTMAP_COMBINED _MIXED_LIGHTING_SUBTRACTIVE
#endif